default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: your_password
  pool: 5

development:
  <<: *default
  database: cafe_cierge_development

test:
  <<: *default
  database: cafe_cierge_test

production:
  <<: *default
  database: cafe_cierge_production
  username: cafe_cierge
  password: <%= ENV['CAFE_CIERGE_DATABASE_PASSWORD'] %>